### ISSUE TITLE
Interface: Global pause and channel pause buttons not working

### ISSUE THREAD

**Issue by jarmitage** [cannc4/Siren#42]
Play works initially but trying to pause thereafter using either interface element doesn't work

**Comment by merttoka** [comment]
This should have been fixed with the latest commits.

**Comment by jarmitage** [comment]
Just testing again, still not working.

Steps
- Launch Siren
- Create new scene
- Add a channel and a pattern
- Click global play, pattern plays
- Click global pause, pattern continues
- Click channel pause, pattern continues

**Comment by cannc4** [comment]
The timer isn't connected to the tidal/audio at all but would make sense to stop/pause the patterns as well.

maybe with a `cps` trick? `cps 0` pauses/stops the tidal patterns 

I think it wouldn't make sense to stop the patterns by _channel timer_ as you might want to pause it and let the pattern

**Comment by cannc4** [comment]
Just to be clear;
The timer in the menubar activates the pulse mechanism of the system,
Once it's active, you can gate the channels individually and start their timers 
At this point, the only connection/sync with Tidal/SC comes via _AbletonLink_ as it's the main pulse source of the system. link will be supported in the next SC release afaik https://github.com/supercollider/supercollider/pull/3351

Would be great to know the expectations from the specific interface objects
eg. should tidal be stopped when the channel is stopped

**Comment by jarmitage** [comment]
This is still unclear I'm afraid but I'm sure we can figure it out.

1. What do you mean by "gate" the channels individually, and "start their timers"? 
2. How is the menubar timer related to the channel timers? 
3. What do these pause buttons actually pause if not the Tidal patterns?
4. How else am I supposed to pause the Tidal patterns if not using the pause buttons?

I think a lot of this confusion stems from that when I initially press Play it play sounds, so when I press Pause I expect it to pause the sound but it doesn't.

**Comment by jarmitage** [comment]
Ok well since this is based on a misunderstanding I will close this for now.
